import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  docs: [
      {
      type: 'autogenerated',
      dirName: 'docs',
    },
  ],
  contribute: [
      {
      type: 'autogenerated',
      dirName: 'contribute',
    },
  ],
  architecture: [
      {
      type: 'autogenerated',
      dirName: 'architecture',
    },
  ],
};

export default sidebars;
